from .category import *
from .page import *
from .register import *
from .login import *
from .restricted import *
from .logout import *
from .about import *
from .index import *
from .search_bing import *
from .profile import *
from .register_profile import *
from .bing_search import *
from .ajax_views import *